// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(securechat_coreFFI)
import securechat_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_securechat_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_securechat_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
                throw CancellationError()

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public protocol NetworkManagerProtocol {
    func getPeerId()   -> String
    func getPeers()   -> [PeerInfo]
    func isRunning()   -> Bool
    func pollEvent()   -> NetworkEvent?
    func start()  throws
    func stop()  
    
}

public class NetworkManager: NetworkManagerProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_securechat_core_fn_free_networkmanager(pointer, $0) }
    }

    

    
    

    public func getPeerId()  -> String {
        return try!  FfiConverterString.lift(
            try! 
    rustCall() {
    
    uniffi_securechat_core_fn_method_networkmanager_get_peer_id(self.pointer, $0
    )
}
        )
    }

    public func getPeers()  -> [PeerInfo] {
        return try!  FfiConverterSequenceTypePeerInfo.lift(
            try! 
    rustCall() {
    
    uniffi_securechat_core_fn_method_networkmanager_get_peers(self.pointer, $0
    )
}
        )
    }

    public func isRunning()  -> Bool {
        return try!  FfiConverterBool.lift(
            try! 
    rustCall() {
    
    uniffi_securechat_core_fn_method_networkmanager_is_running(self.pointer, $0
    )
}
        )
    }

    public func pollEvent()  -> NetworkEvent? {
        return try!  FfiConverterOptionTypeNetworkEvent.lift(
            try! 
    rustCall() {
    
    uniffi_securechat_core_fn_method_networkmanager_poll_event(self.pointer, $0
    )
}
        )
    }

    public func start() throws {
        try 
    rustCallWithError(FfiConverterTypeNetworkError.lift) {
    uniffi_securechat_core_fn_method_networkmanager_start(self.pointer, $0
    )
}
    }

    public func stop()  {
        try! 
    rustCall() {
    
    uniffi_securechat_core_fn_method_networkmanager_stop(self.pointer, $0
    )
}
    }
}

public struct FfiConverterTypeNetworkManager: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = NetworkManager

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NetworkManager {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: NetworkManager, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> NetworkManager {
        return NetworkManager(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: NetworkManager) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public func FfiConverterTypeNetworkManager_lift(_ pointer: UnsafeMutableRawPointer) throws -> NetworkManager {
    return try FfiConverterTypeNetworkManager.lift(pointer)
}

public func FfiConverterTypeNetworkManager_lower(_ value: NetworkManager) -> UnsafeMutableRawPointer {
    return FfiConverterTypeNetworkManager.lower(value)
}


public struct Identity {
    public var publicKeyHex: String
    public var privateKeyHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(publicKeyHex: String, privateKeyHex: String) {
        self.publicKeyHex = publicKeyHex
        self.privateKeyHex = privateKeyHex
    }
}


extension Identity: Equatable, Hashable {
    public static func ==(lhs: Identity, rhs: Identity) -> Bool {
        if lhs.publicKeyHex != rhs.publicKeyHex {
            return false
        }
        if lhs.privateKeyHex != rhs.privateKeyHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(publicKeyHex)
        hasher.combine(privateKeyHex)
    }
}


public struct FfiConverterTypeIdentity: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Identity {
        return try Identity(
            publicKeyHex: FfiConverterString.read(from: &buf), 
            privateKeyHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Identity, into buf: inout [UInt8]) {
        FfiConverterString.write(value.publicKeyHex, into: &buf)
        FfiConverterString.write(value.privateKeyHex, into: &buf)
    }
}


public func FfiConverterTypeIdentity_lift(_ buf: RustBuffer) throws -> Identity {
    return try FfiConverterTypeIdentity.lift(buf)
}

public func FfiConverterTypeIdentity_lower(_ value: Identity) -> RustBuffer {
    return FfiConverterTypeIdentity.lower(value)
}


public struct PeerInfo {
    public var peerId: String
    public var addresses: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(peerId: String, addresses: [String]) {
        self.peerId = peerId
        self.addresses = addresses
    }
}


extension PeerInfo: Equatable, Hashable {
    public static func ==(lhs: PeerInfo, rhs: PeerInfo) -> Bool {
        if lhs.peerId != rhs.peerId {
            return false
        }
        if lhs.addresses != rhs.addresses {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(peerId)
        hasher.combine(addresses)
    }
}


public struct FfiConverterTypePeerInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PeerInfo {
        return try PeerInfo(
            peerId: FfiConverterString.read(from: &buf), 
            addresses: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: PeerInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.peerId, into: &buf)
        FfiConverterSequenceString.write(value.addresses, into: &buf)
    }
}


public func FfiConverterTypePeerInfo_lift(_ buf: RustBuffer) throws -> PeerInfo {
    return try FfiConverterTypePeerInfo.lift(buf)
}

public func FfiConverterTypePeerInfo_lower(_ value: PeerInfo) -> RustBuffer {
    return FfiConverterTypePeerInfo.lower(value)
}


public struct SharedSecret {
    public var secretHex: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(secretHex: String) {
        self.secretHex = secretHex
    }
}


extension SharedSecret: Equatable, Hashable {
    public static func ==(lhs: SharedSecret, rhs: SharedSecret) -> Bool {
        if lhs.secretHex != rhs.secretHex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(secretHex)
    }
}


public struct FfiConverterTypeSharedSecret: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SharedSecret {
        return try SharedSecret(
            secretHex: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: SharedSecret, into buf: inout [UInt8]) {
        FfiConverterString.write(value.secretHex, into: &buf)
    }
}


public func FfiConverterTypeSharedSecret_lift(_ buf: RustBuffer) throws -> SharedSecret {
    return try FfiConverterTypeSharedSecret.lift(buf)
}

public func FfiConverterTypeSharedSecret_lower(_ value: SharedSecret) -> RustBuffer {
    return FfiConverterTypeSharedSecret.lower(value)
}

public enum NetworkError {

    
    
    // Simple error enums only carry a message
    case AlreadyRunning(message: String)
    
    // Simple error enums only carry a message
    case NotRunning(message: String)
    
    // Simple error enums only carry a message
    case StartFailed(message: String)
    
    // Simple error enums only carry a message
    case ConnectionFailed(message: String)
    

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeNetworkError.lift(error)
    }
}


public struct FfiConverterTypeNetworkError: FfiConverterRustBuffer {
    typealias SwiftType = NetworkError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NetworkError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .AlreadyRunning(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .NotRunning(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .StartFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .ConnectionFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NetworkError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .AlreadyRunning(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .NotRunning(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .StartFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .ConnectionFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))

        
        }
    }
}


extension NetworkError: Equatable, Hashable {}

extension NetworkError: Error { }

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
public enum NetworkEvent {
    
    case listening(address: String)
    case peerDiscovered(peer: PeerInfo)
    case peerDisconnected(peerId: String)
    case error(message: String)
}

public struct FfiConverterTypeNetworkEvent: FfiConverterRustBuffer {
    typealias SwiftType = NetworkEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NetworkEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .listening(
            address: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .peerDiscovered(
            peer: try FfiConverterTypePeerInfo.read(from: &buf)
        )
        
        case 3: return .peerDisconnected(
            peerId: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .error(
            message: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NetworkEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .listening(address):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(address, into: &buf)
            
        
        case let .peerDiscovered(peer):
            writeInt(&buf, Int32(2))
            FfiConverterTypePeerInfo.write(peer, into: &buf)
            
        
        case let .peerDisconnected(peerId):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(peerId, into: &buf)
            
        
        case let .error(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


public func FfiConverterTypeNetworkEvent_lift(_ buf: RustBuffer) throws -> NetworkEvent {
    return try FfiConverterTypeNetworkEvent.lift(buf)
}

public func FfiConverterTypeNetworkEvent_lower(_ value: NetworkEvent) -> RustBuffer {
    return FfiConverterTypeNetworkEvent.lower(value)
}


extension NetworkEvent: Equatable, Hashable {}



fileprivate struct FfiConverterOptionTypeNetworkEvent: FfiConverterRustBuffer {
    typealias SwiftType = NetworkEvent?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeNetworkEvent.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeNetworkEvent.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterSequenceTypePeerInfo: FfiConverterRustBuffer {
    typealias SwiftType = [PeerInfo]

    public static func write(_ value: [PeerInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypePeerInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PeerInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [PeerInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypePeerInfo.read(from: &buf))
        }
        return seq
    }
}

public func createNetworkManager()  -> NetworkManager {
    return try!  FfiConverterTypeNetworkManager.lift(
        try! rustCall() {
    uniffi_securechat_core_fn_func_create_network_manager($0)
}
    )
}

public func generateIdentity()  -> Identity {
    return try!  FfiConverterTypeIdentity.lift(
        try! rustCall() {
    uniffi_securechat_core_fn_func_generate_identity($0)
}
    )
}

public func getPublicKeyFingerprint(identity: Identity)  -> String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_securechat_core_fn_func_get_public_key_fingerprint(
        FfiConverterTypeIdentity.lower(identity),$0)
}
    )
}

public func getPublicKeyHex(identity: Identity)  -> String {
    return try!  FfiConverterString.lift(
        try! rustCall() {
    uniffi_securechat_core_fn_func_get_public_key_hex(
        FfiConverterTypeIdentity.lower(identity),$0)
}
    )
}

public func performKeyExchange(myIdentity: Identity, theirPublicKeyHex: String)  -> SharedSecret {
    return try!  FfiConverterTypeSharedSecret.lift(
        try! rustCall() {
    uniffi_securechat_core_fn_func_perform_key_exchange(
        FfiConverterTypeIdentity.lower(myIdentity),
        FfiConverterString.lower(theirPublicKeyHex),$0)
}
    )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 24
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_securechat_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_securechat_core_checksum_func_create_network_manager() != 44264) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_securechat_core_checksum_func_generate_identity() != 29756) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_securechat_core_checksum_func_get_public_key_fingerprint() != 1666) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_securechat_core_checksum_func_get_public_key_hex() != 38584) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_securechat_core_checksum_func_perform_key_exchange() != 16349) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_securechat_core_checksum_method_networkmanager_get_peer_id() != 41202) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_securechat_core_checksum_method_networkmanager_get_peers() != 1542) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_securechat_core_checksum_method_networkmanager_is_running() != 8090) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_securechat_core_checksum_method_networkmanager_poll_event() != 45112) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_securechat_core_checksum_method_networkmanager_start() != 10550) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_securechat_core_checksum_method_networkmanager_stop() != 52514) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}